CREATE TABLE IF NOT EXISTS trend(
    token_id VARCHAR(42) NOT NULL,
    display_order INT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT,
    PRIMARY KEY (token_id)
);


CREATE TABLE IF NOT EXISTS admin(
    account_id VARCHAR(42) NOT NULL,
    created_at BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT,
    PRIMARY KEY (account_id)
);